# syntax=docker/dockerfile:1
FROM python:3.10-slim

WORKDIR /workspace

COPY requirements-api.txt .

RUN pip install -r requirements-api.txt

COPY api-endpoints.py .

CMD ["fastapi", "run", "api-endpoints.py"]
